apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: ceph-pod1
  labels:
    app: hadoop
spec:
  selector:
    matchLabels:
      app: hadoop
      tier: ceph-pod1
  #strategy:
#type: Recreate
  template:
    metadata:
      labels:
        app: hadoop
        tier: ceph-pod1
    spec:
      containers:
      - name: ceph-busybox
        image: busybox
        command: ["sleep", "60000"]
      #   volumeMounts:
      #   - name: ceph-vol1
      #     mountPath: /usr/share/busybox
      #     readOnly: false
      # volumes:
      # - name: ceph-vol1
      #   persistentVolumeClaim:
      #     claimName: ceph-claim

# apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
# kind: Deployment
# metadata:
#   name: datanode
#   labels:
#     app: hadoop
# spec:
#   selector:
#     matchLabels:
#       app: hadoop
#       tier: datanode
#   strategy:
#     type: Recreate
#   template:
#     metadata:
#       labels:
#         app: hadoop
#         tier: datanode
#     spec:
#       containers:
#       - image: dmitryzagr/hadoop-datanode:1.2.1-hadoop2.8.1-java8
#         name: datanode
#         env:
#         envFrom:
#           - configMapRef:
#               name: hadoop-env
#         ports:
#         - containerPort: 50010
#           name: datanode
#         volumeMounts:
#         - name: datanode-data
#           mountPath: /hadoop/dfs/name
#         - name: datanode-archives
#           mountPath: /root/hadoop_data
#       volumes:
#       - name: datanode-data
#         emptyDir: {}
#       - name: datanode-archives
# emptyDir: {}